#!/bin/bash
set -e

DOMAIN="turbostream-rs.messijo.com"
UPSTREAM="localhost:8080"
LOG_PREFIX="[setup-caddy-turbo]"

log() {
  echo "$LOG_PREFIX $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

install_caddy() {
  if command -v caddy &> /dev/null; then
    log "Caddy already installed ($(caddy version --quiet 2>/dev/null || echo 'unknown version'))"
    return 0
  fi

  log "Installing Caddy..."
  
  apt-get update -qq
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
  
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  
  apt-get update -qq
  apt-get install -y -qq caddy
  
  log "Caddy installed successfully"
}

configure_ufw() {
  if ! command -v ufw &> /dev/null; then
    log "UFW not installed, installing..."
    apt-get install -y -qq ufw
  fi

  if ufw status 2>/dev/null | grep -q "Status: active"; then
    log "UFW already active, checking rules..."
  else
    log "Configuring UFW..."
  fi

  ufw allow 22/tcp comment 'SSH' 2>/dev/null || true
  ufw allow 80/tcp comment 'HTTP' 2>/dev/null || true
  ufw allow 443/tcp comment 'HTTPS' 2>/dev/null || true
  
  if ! ufw status 2>/dev/null | grep -q "Status: active"; then
    log "Enabling UFW..."
    echo "y" | ufw enable
  else
    log "UFW rules configured"
  fi
  
  ufw status numbered
}

write_caddyfile() {
  CADDYFILE="/etc/caddy/Caddyfile"
  NEW_CADDYFILE="/etc/caddy/Caddyfile.new"
  
  log "Generating Caddyfile for $DOMAIN..."
  
  cat > "$NEW_CADDYFILE" << 'CADDYEOF'
# Caddyfile for Jetstream Turbo
# Auto-generated by setup-caddy.sh

{
  email admin@messijo.com
}

CADDYEOF

  cat >> "$NEW_CADDYFILE" << CADDYEOF
$DOMAIN {
  reverse_proxy $UPSTREAM
  
  log {
    output file /var/log/caddy/turbo-access.log
    format json
  }
}
CADDYEOF

  mkdir -p /var/log/caddy
  
  if [ -f "$CADDYFILE" ]; then
    if diff -q "$CADDYFILE" "$NEW_CADDYFILE" > /dev/null 2>&1; then
      log "Caddyfile unchanged, skipping reload"
      rm -f "$NEW_CADDYFILE"
      return 0
    else
      log "Caddyfile changed, will reload"
    fi
  else
    log "Creating new Caddyfile"
  fi
  
  mv "$NEW_CADDYFILE" "$CADDYFILE"
  chmod 644 "$CADDYFILE"
  
  log "Caddyfile written to $CADDYFILE"
}

start_caddy() {
  log "Enabling Caddy service..."
  systemctl enable caddy
  
  log "Starting/restarting Caddy..."
  if systemctl is-active --quiet caddy; then
    if [ -f "/etc/caddy/Caddyfile.new" ] || [ "$CADDYFILE_CHANGED" = "true" ]; then
      systemctl reload caddy
      log "Caddy reloaded"
    else
      log "Caddy already running, no reload needed"
    fi
  else
    systemctl start caddy
    log "Caddy started"
  fi
  
  sleep 2
  
  if systemctl is-active --quiet caddy; then
    log "Caddy is running"
    systemctl status caddy --no-pager -l
  else
    log "ERROR: Caddy failed to start"
    journalctl -u caddy --no-pager -n 50
    return 1
  fi
}

verify_dns() {
  log "Verifying DNS resolution for $DOMAIN..."
  
  VPS_IP=$(curl -s https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')
  DOMAIN_IP=$(dig +short "$DOMAIN" A 2>/dev/null | tail -1)
  
  if [ -n "$DOMAIN_IP" ] && [ -n "$VPS_IP" ]; then
    if [ "$DOMAIN_IP" = "$VPS_IP" ]; then
      log "DNS correctly points to this VPS ($DOMAIN_IP)"
    else
      log "WARNING: DNS points to $DOMAIN_IP but this VPS IP appears to be $VPS_IP"
      log "HTTPS may fail until DNS is updated"
    fi
  else
    log "WARNING: Could not verify DNS, HTTPS may fail if DNS not configured"
  fi
}

main() {
  log "Starting Caddy setup for Jetstream Turbo..."
  log "Domain: $DOMAIN"
  log "Upstream: $UPSTREAM"
  
  install_caddy
  configure_ufw
  write_caddyfile
  verify_dns
  start_caddy
  
  log "Setup complete! $DOMAIN should now proxy to $UPSTREAM"
  log "Caddy will automatically provision HTTPS certificates"
}

main "$@"
